CLASS /cc4a/test_check_constant_if1 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS /cc4a/test_check_constant_if1 IMPLEMENTATION.
ENDCLASS.
