CLASS /cc4a/test_check_constant_if1 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS /CC4A/TEST_CHECK_CONSTANT_IF1 IMPLEMENTATION.
ENDCLASS.
